version: '2'

services:
  app:
    build: '.'
    image: 'fr24analyzer'
    ports:
      - '127.0.0.1:8000:8000'
    env_file: '.env'
    command: 'python get.py'
    # volumes:
    #   - 'cachedata:/cache'
    #   - 'mediadata:/media'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata: